Name:           python311-pygobject
Version:        3.44.1
Release:        1%{?dist}
Summary:        Python 3.11 bindings for GObject Introspection

License:        LGPLv2+ and MIT
URL:            https://wiki.gnome.org/Projects/PyGObject
Source0:        pygobject-%{version}.tar.xz

BuildRequires:  gcc
BuildRequires:  meson
BuildRequires:  ninja-build
BuildRequires:  glib2-devel
BuildRequires:  gobject-introspection-devel
BuildRequires:  libffi-devel
BuildRequires:  cairo-devel
BuildRequires:  python3.11-devel
BuildRequires:  python311-pycairo

Requires:       python3.11
Requires:       gobject-introspection
Requires:       python311-pycairo

%description
PyGObject provides Python 3.11 bindings for GObject-based libraries such as
GTK, built for Oracle Linux releases whose stock bindings target an older
interpreter than required by blueman.

%package devel
Summary: Development files for python311-pygobject
Requires: %{name} = %{version}-%{release}
Requires: python311-pycairo-devel

%description devel
Headers and pkg-config file for building software against python311-pygobject.

%prep
%autosetup -n pygobject-%{version}

%build
meson setup _build --prefix=%{_prefix} -Dpython=/usr/bin/python3.11 -Dtests=false
ninja -C _build

%install
DESTDIR=%{buildroot} ninja -C _build install
find %{buildroot} -name '__pycache__' -type d -exec rm -rf {} +
find %{buildroot} -name '*.la' -delete

%files
%license COPYING
%{_prefix}/lib*/python3.11/site-packages/gi/
# pygtkcompat ships with pygobject; its __pycache__ is regenerated by
# brp-bytecompile after the install step, so the whole tree must be packaged
%{_prefix}/lib*/python3.11/site-packages/pygtkcompat/
%{_prefix}/lib*/python3.11/site-packages/PyGObject-*.egg-info

# kept in -devel (not the main package) so the main package never collides
# with the distro's python3-gobject-devel on machines where both are installed
%files devel
%{_includedir}/pygobject-3.0/
%{_libdir}/pkgconfig/pygobject-3.0.pc
